[[main]]
  identifier = "showcase"
  name = "Projects"
  url = "showcase"
  weight = 1



[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 5

  # [[main]]
  # identifier = "pub"
  # name = "Pub"
  # url = "publication"
  # weight = 4


  
